### PR TITLE
Create a profile for a user if one doesn't exist

### PR DESCRIPTION
**Pull request by fluix-dev**
This shouldn't ever happen unless one is creating a superuser with the
manage.py command or creating a user on the admin site. It's best to do
this creation here and not at app startup for example to cause the least
issues and/or confusion.

### CODE REVIEW

**Comment by fluix-dev** [comment]
We should probably try using the `post_save` singal instead, however the `UserView` change to a `DetailView` is still cleaner.

**Comment by dulldesk** [comment]
7eb05b0 should be the last loophole in the current version of the repo. However, for reference, in the future we may need to fetch a user's profile via `Profile.objects.get_or_create()` instead of simply `.get()` until the signal is implemented.

**Review by dulldesk — APPROVED** [review]

**Comment by fluix-dev** [comment]
To clarify, I'm not happy with this -- I'll be changing this to use signals.

**Comment by dulldesk** [comment]
Import statements were missing; otherwise it's working and looks good.

**Review by dulldesk — APPROVED** [review]

**Comment by fluix-dev** [comment]
> Import statements were missing; otherwise it's working and looks good.

Woooops :facepalm:, can you put the two new ones in alphabetical order though (swap them).

**Pull request merged**
