### PR TITLE
UI branch

### LINKED ISSUE #64: Improve Profile UI

### LINKED ISSUE #65: Rework Challenges Cards and Pages

### LINKED ISSUE #66: Add Code Syntax highlighting to Current Markdown parser
Code syntax highlighting is very important in the case of this application as we want our community to insert code snippets and write great tutorials. Without the proper syntax highlighting, the code is very difficult to read.

Right now, we use **[mistune](https://mistune.readthedocs.io/)** as our Python markdown parser. However, it does not have syntax highlighting as part of its core functionality when rendering the text. Thankfully, we can simply extend the parser using the [**Pygments**](https://pygments.org/) library.

An example of how to do this can be seen here: https://mistune.readthedocs.io/en/latest/guide.html?highlight=pygment#customize-renderer

### PR DESCRIPTION
**Pull request by Gongsta**
Branch used for a UI redesign of the entire website. 
This includes an update to the:
- Profile page
- Create challenge/project page
- Challenge/project page.

**Main issues I want to tackle**
**Profile Page:**
- One's own profile page looks constantly like it is in edit mode. I will make it more consolidated to display the most important information, something like this: https://artboard.webflow.io/user-profile

**Create a challenge/project page:**
- The text box is taking a very small section of the page. Other proportions, fonts, and colors, are also a bit awkward.

**Challenge/project page:**
- Will do minor UI tweaks, include sharing options, related challenges section, etc.

### CODE REVIEW

**Comment by fluix-dev** [comment]
> Branch used for a UI redesign of the entire website.

Careful doing everything at once, I don't want this to be another 100 comment thread that's impossible to navigate. Split things up if/where you can.

> One's own profile page looks constantly like it is in edit mode.

The best way to solve this, I believe, is to simply use what others see for your own profile. Assuming you have two buttons in the navbar, `Profile` should go to `/user/name` (once #60 is addressed), while `Edit Profile` would go to `/profile/edit`. The "dashboard" view with your projects, etc. if necessary would be a separate page that would probably contain notifications as well (or maybe separating this would be easy too).

This mimics behavior on a multitude of sites, say GitHub, where github.com/ is your "dashboard", "your profile" goes to your public page like https://github.com/TheAvidDev, and "settings" is always in an editing state.

> The text box is taking a very small section of the page.

Yeah, this should really just be expandable.

**Comment by dulldesk** [comment]
We should also probably choose between `/user/` or `/profile/` in `/user/name` and `/profile/edit` for the sake of consistency. 

> One's own profile page looks constantly like it is in edit mode.

While the above comments are still applicable, `/home/` will show the user's "dashboard" and is not in edit mode.

**Comment by fluix-dev** [comment]
I think the URLs should be:
 - `/user/<name>/` for everyone's public profiles
 - `/user/` for personal dashboard
 - `/settings/` for editing all personal user stuff, for now just your profile

**Edit**: I'll probably do this in a separate PR.

**Comment by Gongsta** [comment]
ok! The only reason I only made one branch is that nobody else has been working on these issues, and it is just 100% more efficient for me to implement all of these changes in one place rather than going 1 at a time, making a PR, waiting for a few days for a review, making changes, repeat, etc. before finally being merged and going onto another issue. You know what I mean? It's a different story if HackItForward was a more polished product, but right now there's still a lot to implement, its still pretty MVP. I'll be careful to make things clear for you to review @TheAvidDev

**Pull request merged**
